version: "3"

vars:
  XDG_DATA_HOME: "{{.HOME}}/.local/share"

env:
  DB_HOST: localhost
  DB_USER:
  DB_PASSWORD:
  DB_NAME: watchyourlan
  DB_PORT:
  DATABASE_URL: "{{.XDG_DATA_HOME}}/watchyourlan/watchyourlan.sqlite"
  AUTH_SECRET: 5N9cgVMUbAWfRufdDkJ3VEPUU/taK6k6DePEVYrt5mY=
  AUTH_TRUST_HOST: http://localhost:3000

tasks:
  run:
    desc: "Run the test application for watchyourlan"
    cmds:
      - bun run ./src/main.ts --url "$(echo ${XDG_DATA_HOME}/watchyourlan/watchyourlan.sqlite)"

  drizzle-gen:
    desc: "Generate the database schema"
    cmds:
      - "mkdir -p {{.XDG_DATA_HOME}}/watchyourlan"
      - bunx drizzle-kit generate --schema ./src/db/schema/*.ts --dialect sqlite

  drizzle-sync:
    desc: "Sync the database with the latest schema"
    cmds:
      - "mkdir -p {{.XDG_DATA_HOME}}/watchyourlan"
      - bunx drizzle-kit push --url $DATABASE_URL --schema ./src/db/schema/*.ts --dialect sqlite
